### ISSUE TITLE
How to add a new ontology?

### ISSUE THREAD

**Issue by brimwats** [anvc/scalar#109]
Hello!

Craig pointed me in this direction!

I'm doing some experimentation with semantic linked data vocabularies and online publishing platforms. I was wondering how I might go about using Homosaurus.org in Scalar? Omeka S had an easy way to add new vocabularies and ontologies, but I don't see that in scalar. I have my own scalar instance spun up on my website.

Thank you!
Brian

**Comment by craigdietrich** [comment]
Hi!

It turns out it's pretty easy!  There are two steps, both described at the top of this file which is also the file you'll need to edit: https://github.com/anvc/scalar/blob/master/system/application/config/rdf.php

You'll need to first define the _prefix_ to _uri_ link in the **$config['namespaces']** array, e.g.,

`'brimwats'   =>  'http://example.com/brimwats/'`

Them, add the fields of the ontology to the **$config['ontologies']** array, e.g.,

```
$config['ontologies']['brimwats'] = array(
  'date', 'time', 'location', 'etc', 'etc'
);
```

The next time you open up the 'Add additional metadata' panel (e.g., on the edit page) you should see 'brimwats' as one of the selectable ontologies, with those fields as items to choose from.  

Finally, fields will be output as "brimwats:location" for HTML and XML and "http://example.com/brimwats/location" for JSON.

Hopefully helpful!

**Comment by brimwats** [comment]
It works very well, thank you!
