### ISSUE TITLE
No input file specified.

### ISSUE THREAD

**Issue by Bicet** [anvc/scalar#133]
I'm try to upgrade scalar, which we plan to use, I don't get why I'm getting "No input file specified." when I try to sign-in, register.
In the home page it works.

https://scalar.gchumanrights.org

I've already tried the suggestion on the closed issues.

**Comment by craigdietrich** [comment]
Hi,

I was able to register just now on your site (you'll see my account in 'All Users' tab in the Dashboard if you've set yourself up as an admin on the install.  So, I'm not sure where to look for the error?  Maybe it is a cookie problem on your browser that could be fixed by clearing your browser history and cookies.

Nb, make sure to add a registration key, otherwise you'll get spammers registering on your install!
https://scalar.usc.edu/works/guide2/local-settings

Cheers,
Craig

**Comment by Bicet** [comment]
The problem was related to php :)
Thanks a lot for registering and for the tip^_^
