### ISSUE TITLE
Get parameters like ?path=index

### ISSUE THREAD

**Issue by dwintergruen** [anvc/scalar#14]
I have installed the git version of scalar. This creates urls with parameters
like ?path=index.

And subsequently I get an 404.

**Comment by craigdietrich** [comment]
Hi @dwintergruen,

We haven't received other reports of GET VARS causing problems on custom installs.  However, the method by which CodeIgniter (Scalar's underlying framework) gets its URLs is in:

system/application/config/config.php

Take a look for:

$config['uri_protocol'] = 'PATH_INFO';

PATH_INFO might not be the appropriate $_SYSTEM variable for your server setup.  The default value is "AUTO" though we noticed this caused more problems then it solved when trying to grab GET VARs from the URL, which is why we switched to PATH_INFO.  However, reverting to AUTO might work for you.

So, the correct value to put there is most likely trial and error (and probably counter-intuitive, since CodeIgniter's URL routing + htaccess also impact the query strings sent to $_SYSTEM).

Thanks,
Craig

**Comment by dwintergruen** [comment]
Great,
thank you this indeed solved it, I had changes PATH_INFO to AUTO because of different problems at the beginning. Now this works.

I have a few other issues with the current version in GIT. It looks like the date generation for the created field is not correct in some models. date(c) is used instead of date(‚Y-m-d H:i:s‘) at different places which leads to an mysql error at least in my setting with a german locale for php.

I also had some minor issues with the settings of the DB. A number of fields are set to not empty but not initialized at the beginning as well as enum doesn’t contain the „“ . I am not sure why this happened I used the sql script in config to generate this.

But after fixing this everthing works very well now on Max OS X 10.10.3 with german settings.

Cheers and Thank you!

**Comment by craigdietrich** [comment]
Hi @dwintergruen -- apologies for the late reply.  We're just now getting back around the scalar_store.sql file and making some adjustments (for example: https://github.com/anvc/scalar/commit/f2145fecae24212af3182da5bbcaab0246d9959a ).  

Are you still experiencing issues with the DB creation?  If so, we could use your assistance weeding out any inconsistencies.  Or, if you've run into any issues with the German language in Scalar?

Thanks!
