### ISSUE TITLE
installing

### ISSUE THREAD

**Issue by shahreahang** [anvc/scalar#156]
Hello,

I want to install this for a customer, could someone please tell me after cloning this and doing configurations how can i access the install page or what is the main page address ? Because I saw there is no index.php in the main folder, could someone please explain this ?

**Comment by craigdietrich** [comment]
The URL is simply the URL to the folder that you put Scalar in.  For example, if you put Scalar in:

`/htdocs/scalar`

... then the URL would be:

`https://myserver.com/scalar`

This is because there is a .htaccess in Scalar's root folder that handles the routing (through codeigniter.php). Make sure that .htaccess makes it into the root folder when you FTP the files (if you're on a Mac, sometimes that file is hidden).

The full install instructions are kept in INSTALL.txt in the root folder. It'll walk you through what needs to be addressed to install Scalar, such as editing the local_settings.php file, database.php file, and others.

**Comment by shahreahang** [comment]
Thank you.
I copied it to a folder and I'm following install instructions, but I get Internal Server Error, However I didn't change anything yet and maybe it's normal but what is the minimum php version required to install this ?

**Comment by craigdietrich** [comment]
Scalar should work on any PHP versions (5 & 7) out in the wild.

Hmm, I haven't heard of a 500 error right out of the box like this.  Is mod_rewrite turned on in the Apache config?
