### ISSUE TITLE
Install fails on mysql:5.7

### ISSUE THREAD

**Issue by paulshannon** [anvc/scalar#26]
[`system/application/config/scalar_store.sql`](https://github.com/anvc/scalar/blob/master/system/application/config/scalar_store.sql#L75) fails with

`ERROR 1067 (42000) at line 71: Invalid default value for 'datetime'`

on mysql version 5.7

**Comment by craigdietrich** [comment]
Thanks for the report, Paul!

Did you recently upgrade to 5.7, and noticed the problem?   There's four places where 'datetime' turns up in the SQL file:

3 are like this:
`created` datetime NOT NULL
The other is like this:
`datetime` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP

I'm guessing it's the NOT NULL in the 3 like statements, since there isn't a default set.  Curious if you could try,  NOT NULL DEFAULT NOW(), and see if that works?

**Comment by paulshannon** [comment]
I was setting up a new install. It's the `NOT NULL DEFAULT '0000-00-00 00:00:00' ON UPDATE CURRENT_TIMESTAMP` that is throwing the error.

I'll try and nail down a fix on monday.

**Comment by craigdietrich** [comment]
Great, thanks for taking a look!

If changes are needed, happy to administer a pull request, or we can add you to the project.

**Comment by paulshannon** [comment]
I think there is some additional compatibility problems with some newer versions of Mysql (couldn't create an account on 5.6). I've reinstalled on 5.5 and it seems to be fine. Probably worth investigating at some point.

**Comment by craigdietrich** [comment]
I've created a ticket in our internal issue tracker, will take a look.  Thanks!
