### ISSUE TITLE
Installation confusion

### ISSUE THREAD

**Issue by stuchalk** [anvc/scalar#37]
I am trying to install scalar by aliasing the folder in apache2 but its not working.
Current config is...

```
﻿﻿<Directory "/pathtoscalarfolder/scalar">
    Options FollowSymLinks
    AllowOverride All
    Order allow,deny
    Allow from all
</Directory>
```

I have tried setting the alias to
`Alias /scalar /pathtosclarafolder/scalar
`and
`Alias /scalar /pathtosclarafolder/scalar/system
`but no luck.
How should this be setup?

**Comment by craigdietrich** [comment]
Hi Stuart,

Thanks for your note!   Is the alias you're setting up masking the URL?  For example, even though the Scalar install is kept at /pathtoscalarfolder/scalar, is the URL that one would use to access Scalar something else, e.g., http://mydomain.com/?

If so, this will break Scalar's URL routing.  Scalar, based on CodeIgniter's underlying URL routing, uses the first URL segment after the install folder (which can be the root folder /) to determine which Scalar "book" is presently being viewed. For example,

http://my-domain.com/scalar/book-url-segment/

If that 'book-url-segment' is masked, so not actually present in the URL, then Scalar would most likely not work properly, or at all.

Curious if this is in the right direction?

**Comment by stuchalk** [comment]
OK, I was able to solve my problem by editing the .htaccess file at the root of the scalar directory structure.  I added `RewriteBase /scalar` after the initial RewriteEngine rule.  But I now have another problem. I now get the following error...

```
A PHP Error was encountered
Severity: 8192
Message: mysql_escape_string(): This function is deprecated; use mysql_real_escape_string() instead.
Filename: mysqli/mysqli_driver.php
Line Number: 304

```
Should I try to fix the PHP code (I use PHPStorm IDE) or just change the error_reporting level?

**Comment by craigdietrich** [comment]
Hi @stuchalk 

Thanks for sticking with this!

I would change the reporting level.  CodeIgniter makes this kind of confusing since it takes over the error handling, so there's a couple places it can be adjusted: in system/application/config/config.php, you can set log_threshold to 0.  But this doesn't always work (for example, on XAMPP I still get errors), in which case you can always adjust error_reporting(E_ALL) to something else in the front controller (codeigniter.php).

There's only one instance where mysql_escape_string is being used, and it's in CodeIgniter, which I don't like to touch.  So, I'd recommend simply suppressing deprecation warnings.  Actually, I just started the process of updating CodeIgniter, so with luck this will resolve itself in a future release.  This is timely since PHP7 pretty much requires us to update CodeIgniter because of it's changes to object oriented syntax.

Thanks!
