### ISSUE TITLE
Question about site import

### ISSUE THREAD

**Issue by jekaanne** [anvc/scalar#39]
We recently migrated our site to Reclaim Hosting because of performance issues, but now the site media links appear to be missing. According to the import/export instructions:

Uploaded media: Media uploaded directly to a source book will not be physically transfered to a destination book. Rather, the destination media pages will point to the URL of the media housed in the source book. This means that in the event that the source book is deleted, the media link will go dead. However, this problem can be corrected using the **"Replace existing" feature at Import > Local media files.** 

When I choose replace existing on the new site, I get an empty dropdown menu. Is this because the site was imported incorrectly, or is this just a limitation of the beta import/export tool? Is there a way to use local files without having to re-upload all of the ~90 images for our site and relink them?

**Comment by craigdietrich** [comment]
Hi @jekaanne,

Thanks for your question!   I'm not sure why the 'replace existing' pulldown wouldn't have values.  You're able to see the media pages in Dashboard > Media tab?  (Scalar is supposed to propagate the Replace Existing pulldown based on that list.)

Nevertheless, the easier way would be to FTP the files (90+) to your Reclaim setup ... there should be a folder for your Scalar book inside the Scalar root folder?  Then inside that, there should be a 'media' folder.

Then, once uploaded via FTP, a simple MySQL query in phpMyAdmin can rewrite the URLs the presently point to the old server with URLs to your new domain.   

I can walk you through this, send a message to http://scalar.usc.edu/contact/ attention: Craig.  I'd be happy to assist.

**Comment by amareshjoshi** [comment]
hi @craigdietrich,
we are in a similar situation. one of our faculty wants move her
scalar site to her online publish publisher.

can you explain which table.columns need to be updated?
i assume this will this leave other metadata associated with
each media file intact?

**Comment by craigdietrich** [comment]
Hi @amareshjoshi,

Right, so, to copy all of the content (and relationships) in a Scalar book you'd use the Import/Export tool in the Dashboard.  But as mentioned after running the transfer the new Scalar book will point to the media at their old URLs in the old Scalar book, rather than transferring the media to its new location (via FTP or whatever).  This is because we generally discourage folks from uploading media directly into Scalar books but rather pointing to materials in our partner archives -- if this has been done then no moving of physical media is needed.

But in the event that physical media has been uploaded to the old Scalar book, it would need to be zipped up and moved to the new Scalar book.  IE, zip up the contents of the book's folder on the server (which is off of the Scalar root folder) and extract it in the folder of the new book.

But after the transfer the URLs in the Scalar book won't point to those physical files on the new Server, so in the event that the old book is deleted those URLs will go dead.  The way to correct that is to open up MySQL, and run these queries:

UPDATE scalar_db_versions   
INNER JOIN scalar_db_content ON scalar_db_versions.content_id = scalar_db_content.content_id 
AND scalar_db_content.book_id = 123 
SET scalar_db_versions.content = REPLACE(scalar_db_versions.content,'http://scalar.usc.edu/works/url-of-old-book/','http://scalar.usc.edu/works/url-of-new-book/');

UPDATE scalar_db_versions   
INNER JOIN scalar_db_content ON scalar_db_versions.content_id = scalar_db_content.content_id 
AND scalar_db_content.book_id = 123 
SET scalar_db_versions.url = REPLACE(scalar_db_versions.url,'http://scalar.usc.edu/works/url-of-old-book/','http://scalar.usc.edu/works/url-of-new-book/');

UPDATE scalar_db_content   
SET scalar_db_content.background = REPLACE(scalar_db_content.background,'http://scalar.usc.edu/works/url-of-old-book/','http://scalar.usc.edu/works/url-of-new-book/') 
WHERE scalar_db_content.book_id = 123;

(To get the book_id, either look it up in the scalar_db_books table or look at the <meta> book_id tag in the HTML.)

Let me know if this works?

**Comment by amareshjoshi** [comment]
hi @craigdietrich,
thanks! that worked, but i noticed a couple of other places
that referenced  the original book (banner and thumbnail). 
also many of the "intra-book" links used an absolute URL with 
the site name in it. so these had to be changed as well. 

here's what i finally used
```
set @title = "Clone Copy";
set @old_url = "http://foo.org/original/book/";
set @new_url = "http://bar.com/clone/copy/";
UPDATE
scalar_db_versions   
INNER JOIN
scalar_db_content ON scalar_db_versions.content_id = scalar_db_content.content_id 
AND scalar_db_content.book_id = (SELECT book_id FROM scalar_db_books WHERE title = @title)
SET
scalar_db_versions.content = REPLACE(scalar_db_versions.content, @old_url, @new_url);
--
UPDATE
scalar_db_versions   
INNER JOIN
scalar_db_content ON scalar_db_versions.content_id = scalar_db_content.content_id 
AND scalar_db_content.book_id = (SELECT book_id FROM scalar_db_books WHERE title = @title)
SET
scalar_db_versions.url = REPLACE(scalar_db_versions.url, @old_url, @new_url),
scalar_db_versions.content = REPLACE(scalar_db_versions.content, @old_url, @new_url);
--
UPDATE
scalar_db_content   
SET
scalar_db_content.background = REPLACE(scalar_db_content.background, @old_url, @new_url),
scalar_db_content.banner = REPLACE(scalar_db_content.banner, @old_url, @new_url),
scalar_db_content.thumbnail = REPLACE(scalar_db_content.thumbnail, @old_url, @new_url)
WHERE
scalar_db_content.book_id = (SELECT book_id FROM scalar_db_books WHERE title = @title);
```

**Comment by craigdietrich** [comment]
@amareshjoshi Wow, this is fantastic!  I'll go ahead and create a new page in the Scalar 2 Guide and put this in there, with credit to you (assuming that's okay).
