### ISSUE TITLE
Error Reporting Levels

### ISSUE THREAD

**Issue by paulshannon** [anvc/scalar#5]
There are several places where the error reporting level is being overridden to display all errors.

https://github.com/anvc/scalar/search?utf8=%E2%9C%93&q=error_reporting

It would be much better to have this as a configuration option. For instance, I'm getting lots of Deprecation errors from the mysql_* functions.

**Comment by craigdietrich** [comment]
Thanks for reporting this, Paul.  I'm going to start tackling this, removing error reporting functions system/application in favor of CodeIgniter's reporting level kept in config.php

**Comment by craigdietrich** [comment]
Following up on this front way late!

A recent commit removes the error reporting calls, placing management of this back into the hands of CodeIgniter.  The latter can be managed under system/application/config/config.php.  By default it places errors and messages into a file at system/logs rather than display them on the front end.
