### ISSUE TITLE
Omeka Classic media source hardcodes insecure URL

### ISSUE THREAD

**Issue by crism** [anvc/scalar#63]
in `system/application/rdf/omeka_to_json.php`, the given Omeka URL has its scheme stripped, and then `http://` prepended. If the Omeka installation is running over HTTPS, it is inaccessible to Scalar.

**Comment by craigdietrich** [comment]
Hi @crism 

I feel there is/was some reason I did that, having to do with Scalar not being well-functioning under https (because many of the plugins it incorporates don't run under https, we wouldn't be able to embed them).  But of course since the import mechanism is via a php proxy it's kind of a mute point.

In any event, Scalar's import mechanism is in the process of being replaced by a new tool called Tensor, so I'm inclined to let this go as we'll have a fresh new Omeka importer in Tensor (that hopefully can auto-adjust to the various Omeka API versions).

**Comment by crism** [comment]
Thanks, @craigdietrich. We need the Omeka connection working pretty soon, and I think this is a pretty straightforward fix, so I’m going to try to get it done. What’s the timeline for Tensor?

**Comment by craigdietrich** [comment]
Scalar's /external page is also vulnerable to simply including spam pages inside its iframe ... though I'm not really sure how to protect that since in principle it's supposed to show any external page with Scalar's header at the top.

**Comment by craigdietrich** [comment]
Re Tensor, it's actually working right now but certainly in "alpha" https://github.com/anvc/tensor .. I'm sort of timid to roll it out inside Scalar itself (it can operate on its own, actually) until I fill out a few more parsers for large archive systems such as CONTENTdm https://github.com/craigdietrich/tensor-profiles .

**Comment by crism** [comment]
Thanks, @craigdietrich, for the Tensor update. I’m sending a PR for this issue, but will take a look at Tensor, too.

**Comment by craigdietrich** [comment]
Able to put this as a pull request?
