### ISSUE TITLE
Disable Registration

### ISSUE THREAD

**Issue by paulshannon** [anvc/scalar#7]
There should be a simple way to disable registration

**Comment by craigdietrich** [comment]
@paulshannon Are you envisioning a protection beyond the "registration key" available in local_settings.php?  Ie, removing the registration page entirely so no one can register or even know that they can register with a key?

**Comment by paulshannon** [comment]
I don't know what that setting does. I don't see any documentation on it.

**Comment by craigdietrich** [comment]
If you place a string(s) in this array in local_settings.php...
```
// Register key (leave blank if no register key required, e.g., array())
$config['register_key'] = array();
```
... it will add a form field to the registration page called, "Registration key".  New users will have to enter the key (or one of the keys) in order to register, otherwise the page will return an error message.

Let me know if this is sufficient for your needs or if you're looking for something more advanced?

**Comment by paulshannon** [comment]
That's fine for my immediate needs. Thanks!
