### ISSUE TITLE
Scalar upgrade

### ISSUE THREAD

**Issue by pguerr061703** [anvc/scalar#74]
Hello, I am currently at scalar version 2.1.1  on Redhat 6 virtual host. How do I upgrade to the latest version of Scalar? Is it version 2.7 ? Where do I get the latest version? Does the mysql database get ugpraded as well? Please inform how to perform this upgrade and what potentially can go wrong.

use cannot see images on current version. They appear as <question marks>. I was told an upgrade will fix this. Please send me everything i need to do and look out for, so I don't break what I currently have (mysql 5.7, scalar 2.1.1, httpd web service). thank you kindly

**Comment by eloyer** [comment]
@pguerr061703 Have you checked out [UPDATE.txt](https://github.com/anvc/scalar/blob/master/UPDATE.txt)?

**Comment by pguerr061703** [comment]
I did review that document. How do I know if the upgrade is successful? Where would I find the version number (2.1.7) on the scalar site after the upgrade ? Is it listed somewhere? Can you provide additional assistance?

**Comment by craigdietrich** [comment]
First, you can get the newest release here: https://github.com/anvc/scalar/releases .. simply download and extract the ZIP.

Then, follow the instructions under the heading "INSTRUCTIONS FOR UPDATING TO SCALAR 2.1.x FROM SCALAR 2.1 OR SCALAR 2.1.1", here: https://github.com/anvc/scalar/blob/master/UPDATE.txt  Really all you're doing is copying what's in the system/application folder to your webserver making sure to not overwrite the config files you already have filled out.

Finally, head over here and see if you need to make any updates to those config files or your database: https://github.com/anvc/scalar/wiki/Changes-to-config-files-over-time  Since Scalar version 2.1 (which you say you are on now) was release Aug 20, 2016, you'll want to start at "Update: 14 September 2016" on the list and work your way up.  It should all be straight forward, adding a few values here and there. For example, that first update (14 Sep 2016) adds ReCAPTCHA v2 support which is important since Google is deprecating ReCAPTCHA v1 in March 2018.

That's it!  Scalar should work as expect but now you should notice the new widgets feature, enhanced annotation management, etc., ie, features described on our blog at scalar.usc.edu.

Once you're updated you can confirm by look at the "scalar-version.php" file here: https://github.com/anvc/scalar/tree/master/system/application/views

**Comment by pguerr061703** [comment]
My site became unresponsive because of this line that I added from  December 2016

Update: 11 December 2016
Add to $config['namespaces'] in system/application/config/rdf.php
**'id3' => 'http://id3.org/id3v2.4.0#'**

As soon as I  removed that line (id3 => id3.org/id3v2.4.0#) in rdf.php file,  my Scalar site came right up.(online)
Can you please confirm the syntax . This is what I originally had in my rdf.php (See last lines below)

$config['namespaces'] = array(
                                        'rdf'       => 'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
                                    'rdfs'      => 'http://www.w3.org/2000/01/rdf-schema#',
                                                'dc'        => 'http://purl.org/dc/elements/1.1/',
                                                'dcterms'   => 'http://purl.org/dc/terms/',
                                                'ctag'      => 'http://commontag.org/ns#',
                                                'art'       => 'http://simile.mit.edu/2003/10/ontologies/artstor#',
                                                'sioc'      => 'http://rdfs.org/sioc/ns#',
                                                'sioctypes' => 'http://rdfs.org/sioc/types#',
                                                'foaf'      => 'http://xmlns.com/foaf/0.1/',
                                                'owl'       => 'http://www.w3.org/2002/07/owl#',
                                                'ov'            => 'http://open.vocab.org/terms/',
                                                'oac'           => 'http://www.openannotation.org/ns/',
                                                'scalar'    => 'http://scalar.usc.edu/2012/01/scalar-ns#',
                                                'shoah'         => 'http://tempuri.org/',
                                                'prov'          => 'http://www.w3.org/ns/prov#',
                                                'exif'          => 'http://ns.adobe.com/exif/1.0/',
                                                'iptc'          => 'http://ns.exiftool.ca/IPTC/IPTC/1.0/',
                                                'bibo'          => 'http://purl.org/ontology/bibo/'
                                                 **id3            => '=> id3.org/id3v2.4.0#'**
                                           );

**Comment by pguerr061703** [comment]
I also still have problems determining the VERSION upgrade was successful.
I went to my site's URL <scalar<domain>.edu/system/application/views/scalar-version.php
However the output from the URL said  "No direct script access allowed".

Please let me know HOW to confirm the UPGRADE was successful.

**Comment by craigdietrich** [comment]
> I also still have problems determining the VERSION(2.1.7) upgrade was successful.
> I went to my site's URL https://scalar.[universitydomain].edu/system/application/views/scalar-version.php
> However the output from the URL said "No direct script access allowed".
> 
> Please let me know HOW to confirm the UPGRADE was successful.

View the file on the filesystem (e.g., FTP) not via the web browser.

**Comment by craigdietrich** [comment]
> As soon as I removed that line (id3 => id3.org/id3v2.4.0#) in rdf.php file, my Scalar site came right up.(online)
> Can you please confirm the syntax . This is what I originally had in my rdf.php (See last lines below)

PHP arrays need commas (",") after each line item.  So, in the example you posted you need to add a comma after the second-to-last line, like this:

'bibo' => 'http://purl.org/ontology/bibo/',

Then, you'll be safe to add a new last line like you did (the ID3 line).

**Comment by pguerr061703** [comment]
The upgrade did NOT solve the problem with the media gallery. Its still not displaying images.

I just created a quick book, and am still having problems with the thumbnails of images not rendering correctly:

https://scalar.[universitydomain].edu/car-test-book/test-of--structured-media-gallery 

![media-gallery](https://user-images.githubusercontent.com/12171475/31902085-9d5b45de-b7f1-11e7-9cf0-8ddc8b7a5ba9.PNG)

but Media Gallery works:

https://scalar.[universitydomain].edu/car-test-book/test-of-media-gallery

![media-gallery2](https://user-images.githubusercontent.com/12171475/31902095-a813c136-b7f1-11e7-9724-40ed99033b45.PNG)

The thumbnails aren't showing correctly in Test of Structured Media Gallery, they show up as grey, generic icons.

Otherwise, the upgrade looks great.  No problems other than the icons of media / Images.
What can be done to fix this? Maybe the upgrade to 2.1.7 did not work ? or something went wrong.

**Comment by eloyer** [comment]
The other possibility could be that those media items don't have thumbnails. If you edit one of the pieces of media in question, go down to the Styling tab and select Thumbnail, is anything set?

**Comment by craigdietrich** [comment]
The reason thumbnails aren't showing for those media is because those media don't have thumbnails.  You need to go to each media-page (ie, the page that is just the media file), edit it (pen icon), then under the Styling tab on the edit page, enter a thumbnail.  

From the looks of the Media Gallery those are YouTube videos ... if you use the built-in YouTube importer (Tray icon > Other archives > YouTube) it'll import the thumbnail automatically.  The only way that it could have been included in Scalar _without_ a thumbnail is if they had been added by hand (Tray icon > Internet Media Files).  I'm not sure why you'd go this latter route rather than the former, built-in method; I'd definitely suggest the built-in method!

**Comment by pguerr061703** [comment]
Okay, great.  I am now able to get/generate thumbnails.

The other issue that your first github respondent mentioned (and I'd just given up on it) is that  you are supposed to be able to import, say, Youtube videos with appropriate thumbnails and metadata by doing this:

Inline image 1

Sadly, that results in this:

Inline image 2

**Comment by craigdietrich** [comment]
Seems there's an internal server error :)

Check to make sure the .htaccess file is present on your server in /system/application/rdf, i.e., here:

https://github.com/anvc/scalar/tree/master/system/application/rdf

It's needed to allow requests from the Import pages through to the XSL parser. If you're managing your server with a Mac chances are your FTP client hid the .htaccess file, since dot files are hidden on a Mac, and thus didn't transfer it to the server.

If it is there, the other problem is likely that you don't have the XSL library turned on in PHP (http://php.net/manual/en/xsl.installation.php), though it's usually on by default.

Either way if you turn on your browsers Web Inspector and check out the Ajax request happening in the background when you run the search it should tell you what's going on in the Response of niether of the above work.

**Comment by pguerr061703** [comment]
Thank you, I checked, but the .htaccess is already there, so it must be something else (XSL) library
[root@ace-linux11 rdf]# pwd
/var/www/html/scalar/system/application/rdf
[root@ace-linux11 rdf]# more .htaccess
Satisfy Any
Allow from all
[root@ace-linux11 rdf]#

I couldn't find XSL library on my Scalar server for Redhat 6, unfortunately
[root@linux11 rdf]# rpm -qa |grep php5-xsl
[root@linux11 rdf]#
 
Where can I get that library for Redhat 6.x ?  
Thank you for all  of your help!!

**Comment by craigdietrich** [comment]
Unfortunately installing (or enabling) PHP extensions is a bit out of the set of the things I can assist with.  

Usually you can edit php.ini and it may be simply commented out there; uncommenting it and restarting PHP can get it running.  But this is just speculation.

Do you have a server admin on your side you can talk to?

**Comment by pguerr061703** [comment]
I'm the admin. So I noticed that xsl is already installed and working:

Tested  via php -i | grep xsl --> Results show its working 
/etc/php.d/xsl.ini,
xsl
libxslt Version => 1.1.26
libxslt compiled against libxml Version => 2.7.6
libexslt Version => 1.1.26
https://crappylabs.wordpress.com/2016/12/17/installing-php-xsl-extension-on-centos-7/

Also the .htaccess is already there and configured 

[root@linux11 rdf]# more .htaccess
Satisfy Any
Allow from all
[root@linux11 rdf]# pwd
/var/www/html/scalar/system/application/rdf
[root@linux11 rdf]#
[root@linux11 rdf]# ls -la .htaccess
-rwxrwxr-x 1 apache apache 27 Oct 15 21:13 .htaccess

Is there any other reason why the internal server error would come from the youtube import? 
Are ports needed to be open on the server? 
![screen shot 2017-10-23 at 2 01 20 pm 1](https://user-images.githubusercontent.com/12171475/31949357-1bf1e730-b8a7-11e7-9105-573f4588a964.jpg)
![screen shot 2017-10-23 at 2 02 04 pm 1](https://user-images.githubusercontent.com/12171475/31949363-2189f67e-b8a7-11e7-9435-adb3e1838afc.jpg)

**Comment by pguerr061703** [comment]
I need additional help. User is complaining that the import button is greyed out.
"
The ability to do so was working yesterday morning, so I'm confused as to why this is now happening.  When I try to import a local media file, (and yes, I've tried all permutations of the form, below) I can't click on "Upload":"
![image](https://user-images.githubusercontent.com/12171475/31953057-34cca502-b8b0-11e7-9bcb-755302cc91f3.png)

**Comment by craigdietrich** [comment]
It seems you have something on the server causing internal problems with both the import pages and the upload page.

I'd suggest opening up the Web Inspector on your browser, head over to the Network tab, and then run some imports and some uploads.  When you do these actions the Network panel will show the actual requests being sent to the server.  You can open up each request and look at the Response, which will display any internal problems, hopefully.
