### ISSUE TITLE
Migrating On-Premise Scalar Application to Cloud PaaS Framework 

### ISSUE THREAD

**Issue by TayiSaiKishore** [anvc/scalar#84]
Greetings Team, 

Currently, we are using 2.17 Scalar which is hosted on our local server. 
However, our future plans are hosting application on cloud - PaaS framework. So, looking for any reference document for the same.  

Thanks In Advance.

**Comment by craigdietrich** [comment]
Hi!

Really shouldn't be too much too it.  You could simply set up Scalar on that new server, copy the MySQL database, and copy the project folders kept in the Scalar root directory.  This is if you wanted an exact copy.

Less exact would be to use our Import/Export tool https://github.com/Michael628/scalar-book-transfer-tool, though this requires a little more nuance.

So, I think in conclusion you shouldn't need to worry too much about moving forward with your Scalar install now, since you'll be able to transfer it later.

**Comment by TayiSaiKishore** [comment]
Hello Team,

Thanks for the update.
However, we are testing in house.

Hosted webapp in azure with mysql backend.
Copied all required files. However, while accessing test link we see

[cid:image001.png@01D3A1B7.3461AD20]

**Comment by craigdietrich** [comment]
Seems to be the azure service (which I don't really know anything about) isn't running Apache and/or doesn't have mod_rewrite active such that .htaccess is being activated.

**Comment by TayiSaiKishore** [comment]
Is there any framework diagram or workflow available ?
how can we integrate scalar application with our active directory ?

Please help.

**Comment by craigdietrich** [comment]
We (the scalar team) don't have any experience integrating Active Directory, and I don't know of anyone else that has (at least that we've heard of).

Of course, if you come up with something let us know and run a pull request!

**Comment by craigdietrich** [comment]
Scalar's underlying framework is CodeIgniter 2.x, so any core hookups would be documented there: https://codeigniter.com/userguide2/
