### ISSUE TITLE
rewrite path header using innerhtml

### ISSUE THREAD

**Issue by rcrath** [anvc/scalar#85]
Hi, I am trying to rewrite the H1 header that is autogenerated at the top of the path on the [home page of this site](http://dahi.manoa.hawaii.edu/scalar2/the-souls-of-black-folk/index).  Instead of saying "Contents" I want it to say "herein is written" as in the original TOC.  I tried this javascript addition on the styling page with no luck:
```
document.getElementById("herein").innerHTML = "Herein is Written";
```
but was unable to get the ID into the html that was autogenerated by the path.  

Is there any way to do this?

**Comment by craigdietrich** [comment]
You'd need to place inside a load event.  But also, Scalar has its own load event since there's some DOM manipulation that occurs even after the page load event.

$(document).ready(function() {
  $('body').on('pageLoadComplete', function() {
    $('herein').html('Herein is Written');
  });
});

Note that you can get to the page's title (the H1 page title) like this:

$(document).ready(function() {
  $('body').on('pageLoadComplete', function() {
    $('h1[property="dcterms:title"]').html('Herein is Written');
  });
});

**Comment by rcrath** [comment]
Hi Craig, Thanks for responding.  I am new to APIs and js but trying to learn, so thanks for your patience.  I pasted the first snippet into the style/js field, but I can't figure out how to get the path h1 tag to render with the `id="herein"` element in the HTML, so it does not rewrite.  This is probably basic, but I was not able to find how to do this in the api reference.

**Comment by craigdietrich** [comment]
There are only two &lt;h1&gt; tags on the page you reference:
1) The title of the page ("The Souls of Black Folk")
2) The header of the path contents ("Contents")

Also, you're trying to reference a tag with id="herein" while there isn't any tag with that ID in the page.  Is the idea to add that ID to one of the two &lt;h1&gt; tags above in order to be able to style it with CSS?  If so, this will add id="herein" to the page title (the first &lt;h1&gt; tag):

```
$(document).ready(function() {
  $('h1[property="dcterms:title"]').attr('id', 'herein');
});
```

If you wanted to place the ID on the second &lt;h1&gt; tag (the path contents header):

```
$(document).ready(function() {
  $('.path_of').prev().attr('id', 'herein');
});
```

And, in CSS, this would style it:

`#herein {color:red;}`

Let me know if this is what you are looking for?

**Comment by rcrath** [comment]
Yes, that and the first snippet together did the job.  Thank you @craigdietrich .
