### ISSUE TITLE
Title in Navbar gets not displayed on Chromium/Ubuntu

### ISSUE THREAD

**Issue by mogoh** [anvc/scalar#89]
![bildschirmfoto von 2018-04-25 15-21-53](https://user-images.githubusercontent.com/580975/39248497-89e04bb2-489c-11e8-98a2-f8bc2c0a16d3.png)

I can only reproduce this bug on Chromium and Ubuntu. It is very strange.

This is the HTML Element:

    <span class="navbar-text navbar-left pull-left title_wrapper hidden-xs withTooltip overflowCalculated" id="desktopTitleWrapper" style="max-width: 896px; word-wrap: break-word;" data-original-title="" title=""></span>

**Comment by plusperturbatio** [comment]
Howdy! I may have isolated the issue (it's one I've been tackling on and off for a while) - do you happen to have a Scalar install of your own? If so, if you could try replacing the scalarheader.jquery.js file located in \system\application\views\melons\cantaloupe\js with the attached zipped file:
[scalarheader.zip](https://github.com/anvc/scalar/files/1947822/scalarheader.zip)

Otherwise, I just pushed a commit with the change so it should eventually propagate. Hopefully that change resolves the issue (once it goes live.)

**Comment by mogoh** [comment]
> do you happen to have a Scalar install of your own?

No, sorry. :(

> Otherwise, I just pushed a commit with the change so it should eventually propagate. Hopefully that change resolves the issue (once it goes live.)

Great, thank you! :)

**Comment by mogoh** [comment]
@craigdietrich Yes, thanks. :)

Sorry, for answering late. :/
