### ISSUE TITLE
Migrate books and data from Scalar to new Scalar host

### ISSUE THREAD

**Issue by pguerr061703** [anvc/scalar#93]
Hello, I recently created a new Scalar host with latest version 2.1.10 on a virtual Ubuntu 16.04 host.  I want to copy all the users and associated books from my old scalar host (Redhat 6 , Scalar version 2.1.2 (i think))..

Is there a migration tool to copy the users  and books over   to  my new Ubuntu host?
Should I consider doing a mysqldump (export) and import ?  folders to copy on server? 

What would be a good way to get all the users and associated books over ?  I have 60+ users and books.

Thank you

**Comment by craigdietrich** [comment]
You can set a book to 'Duplicatable' in the Dashboard's Sharing tab, then duplicate it over in the My Account tab.  This will cover _most_ things about a book.

That said I'd just copy the database... I don't think anything has changed on the database front for a long time (see https://github.com/anvc/scalar/wiki/Changes-to-config-files-over-time).  Just make sure the "shasalt" key in local_settings.php is the same between the two Scalar installs otherwise people will need to 'forgot password?' their passwords.
